#! /bin/bash

if [ "$1" == "start" ] || [ "$1" == "stop" ] || [ "$1" == "restart" ]; then
    true
else
    exit 1
fi

./backend.sh $1
./frontend.sh $1
./cdn.sh $1
./parser.sh $1
./scanner.sh $1
./scraper.sh $1
